In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("Datasets/bank.csv")
df=data.copy()
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes


In [3]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
X = df.drop('deposit', axis=1)
y = df['deposit'].map({'yes': 1, 'no': 0})

In [7]:
X.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'],
      dtype='object')

In [8]:
y

0        1
1        1
2        1
3        1
4        1
        ..
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [9]:
X['pdays']

0         -1
1         -1
2         -1
3         -1
4         -1
        ... 
11157     -1
11158     -1
11159     -1
11160    172
11161     -1
Name: pdays, Length: 11162, dtype: int64

In [10]:
print(X['pdays'].value_counts().head(20))
print("\nNumber of -1:", (X['pdays'] == -1).sum())
print("Number of valid pdays:", (X['pdays'] != -1).sum())

pdays
-1      8324
 92      106
 182      89
 91       84
 181      81
 183      73
 184      52
 94       42
 93       41
 95       39
 87       34
 90       32
 98       31
 185      30
 187      28
 97       26
 96       26
 189      24
 188      24
 105      22
Name: count, dtype: int64

Number of -1: 8324
Number of valid pdays: 2838


In [14]:
X['previously_contacted'] = (X['pdays'] != -1).astype(int)

X['pdays'] = X['pdays'].replace(-1, np.nan)
X['previously_contacted'] = X['pdays'].notna().astype(int)
print(X[['pdays', 'previously_contacted']].head(40))

    pdays  previously_contacted
0     NaN                     0
1     NaN                     0
2     NaN                     0
3     NaN                     0
4     NaN                     0
5     NaN                     0
6     NaN                     0
7     NaN                     0
8     NaN                     0
9     NaN                     0
10    NaN                     0
11    NaN                     0
12    NaN                     0
13    NaN                     0
14    NaN                     0
15    NaN                     0
16    NaN                     0
17    NaN                     0
18    NaN                     0
19    NaN                     0
20    NaN                     0
21    NaN                     0
22    NaN                     0
23    NaN                     0
24    NaN                     0
25    NaN                     0
26    NaN                     0
27    NaN                     0
28    NaN                     0
29    NaN                     0
30    Na

In [16]:
X['previously_contacted'].value_counts()

previously_contacted
0    8324
1    2838
Name: count, dtype: int64

In [17]:
categorical_cols = [
    'job',
    'marital',
    'education',
    'default',
    'housing',
    'loan',
    'contact',
    'month',
    'poutcome'
]
for col in categorical_cols:
    print(f"\n{col}:")
    print(X[col].value_counts())


job:
job
management       2566
blue-collar      1944
technician       1823
admin.           1334
services          923
retired           778
self-employed     405
student           360
unemployed        357
entrepreneur      328
housemaid         274
unknown            70
Name: count, dtype: int64

marital:
marital
married     6351
single      3518
divorced    1293
Name: count, dtype: int64

education:
education
secondary    5476
tertiary     3689
primary      1500
unknown       497
Name: count, dtype: int64

default:
default
no     10994
yes      168
Name: count, dtype: int64

housing:
housing
no     5881
yes    5281
Name: count, dtype: int64

loan:
loan
no     9702
yes    1460
Name: count, dtype: int64

contact:
contact
cellular     8042
unknown      2346
telephone     774
Name: count, dtype: int64

month:
month
may    2824
aug    1519
jul    1514
jun    1222
nov     943
apr     923
feb     776
oct     392
jan     344
sep     319
mar     276
dec     110
Name: count, dtype: int64

po

In [18]:
categorical_cols = [
    'job',
    'marital',
    'education',
    'default',
    'housing',
    'loan',
    'contact',
    'month',
    'poutcome'
]

numeric_cols = [
    'age',
    'balance',
    'day',
    'duration',
    'campaign',
    'pdays',
    'previous',
    'previously_contacted'
]

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsClassifier

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [23]:
categorical_transformer = OneHotEncoder(
    handle_unknown='ignore'
)

In [25]:

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

In [26]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [27]:
print("Before preprocessing:", X_train.shape)
print("After preprocessing:", X_train_processed.shape)

print("Test before preprocessing:", X_test.shape)
print("Test after preprocessing:", X_test_processed.shape)

Before preprocessing: (8929, 17)
After preprocessing: (8929, 52)
Test before preprocessing: (2233, 17)
Test after preprocessing: (2233, 52)


In [28]:
print("NaN in training:", np.isnan(X_train_processed).sum())
print("NaN in testing:", np.isnan(X_test_processed).sum())

NaN in training: 0
NaN in testing: 0


In [32]:

knn = KNeighborsClassifier(n_neighbors=5)

In [33]:
knn.fit(X_train_processed, y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [34]:
y_pred = knn.predict(X_test_processed)

In [35]:
print(y_pred[:20])

[1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1]


In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8186296462158531

Confusion Matrix:
[[993 182]
 [223 835]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.85      0.83      1175
           1       0.82      0.79      0.80      1058

    accuracy                           0.82      2233
   macro avg       0.82      0.82      0.82      2233
weighted avg       0.82      0.82      0.82      2233



In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

results = []

for k in range(1, 21):
    knn = KNeighborsClassifier(n_neighbors=k)
    
    knn.fit(X_train_processed, y_train)
    
    y_pred_k = knn.predict(X_test_processed)
    
    accuracy = accuracy_score(y_test, y_pred_k)
    
    results.append((k, accuracy))

for k, accuracy in results:
    print(f"K = {k:2d}  Accuracy = {accuracy:.4f}")

K =  1  Accuracy = 0.7703
K =  2  Accuracy = 0.7403
K =  3  Accuracy = 0.7967
K =  4  Accuracy = 0.7738
K =  5  Accuracy = 0.8186
K =  6  Accuracy = 0.7980
K =  7  Accuracy = 0.8231
K =  8  Accuracy = 0.8061
K =  9  Accuracy = 0.8209
K = 10  Accuracy = 0.8070
K = 11  Accuracy = 0.8249
K = 12  Accuracy = 0.8110
K = 13  Accuracy = 0.8195
K = 14  Accuracy = 0.8079
K = 15  Accuracy = 0.8177
K = 16  Accuracy = 0.8074
K = 17  Accuracy = 0.8177
K = 18  Accuracy = 0.8092
K = 19  Accuracy = 0.8164
K = 20  Accuracy = 0.8074


In [41]:
best_k, best_accuracy = max(results, key=lambda x: x[1])

print("Best K:", best_k)
print("Best Accuracy:", best_accuracy)

Best K: 11
Best Accuracy: 0.8248992386923422


In [42]:

# Create KNN model with best K
knn = KNeighborsClassifier(n_neighbors=11)

# Train the model
knn.fit(X_train_processed, y_train)

# Predict on test data
y_pred = knn.predict(X_test_processed)

In [43]:
# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Test Accuracy:", accuracy)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Test Accuracy: 0.8248992386923422

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84      1175
           1       0.83      0.79      0.81      1058

    accuracy                           0.82      2233
   macro avg       0.83      0.82      0.82      2233
weighted avg       0.83      0.82      0.82      2233


Confusion Matrix:
[[1010  165]
 [ 226  832]]
